
package wesessionlogin;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EventHandlerService", targetNamespace = "http://eh.actimize.com", wsdlLocation = "http://172.18.34.62:2347/eh/service/EventHandlerService?wsdl")
public class EventHandlerService
    extends Service
{

    private final static URL EVENTHANDLERSERVICE_WSDL_LOCATION;
    private final static WebServiceException EVENTHANDLERSERVICE_EXCEPTION;
    private final static QName EVENTHANDLERSERVICE_QNAME = new QName("http://eh.actimize.com", "EventHandlerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.18.34.62:2347/eh/service/EventHandlerService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EVENTHANDLERSERVICE_WSDL_LOCATION = url;
        EVENTHANDLERSERVICE_EXCEPTION = e;
    }

    public EventHandlerService() {
        super(__getWsdlLocation(), EVENTHANDLERSERVICE_QNAME);
    }

    public EventHandlerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EVENTHANDLERSERVICE_QNAME, features);
    }

    public EventHandlerService(URL wsdlLocation) {
        super(wsdlLocation, EVENTHANDLERSERVICE_QNAME);
    }

    public EventHandlerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EVENTHANDLERSERVICE_QNAME, features);
    }

    public EventHandlerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EventHandlerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EHProxy
     */
    @WebEndpoint(name = "EventHandlerServiceHttpPort")
    public EHProxy getEventHandlerServiceHttpPort() {
        return super.getPort(new QName("http://eh.actimize.com", "EventHandlerServiceHttpPort"), EHProxy.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EHProxy
     */
    @WebEndpoint(name = "EventHandlerServiceHttpPort")
    public EHProxy getEventHandlerServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://eh.actimize.com", "EventHandlerServiceHttpPort"), EHProxy.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EVENTHANDLERSERVICE_EXCEPTION!= null) {
            throw EVENTHANDLERSERVICE_EXCEPTION;
        }
        return EVENTHANDLERSERVICE_WSDL_LOCATION;
    }

}
